Repository eludris/eludris, pull requests merged in 2023-05, with the labels that each got.

#62 feat(oprish): isolate model logic to its own module
  todel/src/models/files.rs
  todel/src/models/logic/files.rs
  todel/src/models/logic/mod.rs
  todel/src/models/mod.rs
Labels: enhancement

#64 feat: improve eludris IDs
  Cargo.lock
  docs/src/content/extra/detailed.md
  effis/src/main.rs
  migrations/20221128214127_files.sql
  todel/Cargo.toml
  todel/sqlx-data.json
  todel/src/ids/mod.rs
  todel/src/models/files.rs
  todel/src/models/logic/files.rs
Labels: enhancement

#65 feat(pandemonium): share one connection for writing and reading ratelimit info
  pandemonium/src/handle_connection.rs
  pandemonium/src/main.rs
  pandemonium/src/rate_limit.rs
Labels: enhancement

#66 docs: document missing models
  autodoc.py
  autodoc.sh
  cli/src/attachments.rs
  cli/src/main.rs
  codegen/src/autodoc/handle_fn.rs
  codegen/src/autodoc/utils.rs
  docs/src/components/Sidebar.astro
  docs/src/pages/reference/data_to_md.ts
  effis/src/routes/buckets.rs
  effis/src/routes/index.rs
  effis/src/routes/mod.rs
  effis/src/routes/static_routes.rs
  oprish/src/routes/messages/mod.rs
  oprish/src/routes/mod.rs
  todel/src/conf/effis_rate_limits.rs
  todel/src/conf/mod.rs
  todel/src/conf/oprish_rate_limits.rs
  todel/src/models/files.rs
  todel/src/models/gateway.rs
  todel/src/models/info.rs
  todel/src/models/logic/files.rs
  todel/src/models/messages.rs
Labels: documentation

#67 test: improve Eludris testing
  .dockerignore
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  effis/Cargo.toml
  effis/Dockerfile
  effis/src/main.rs
  effis/src/rate_limit.rs
  effis/src/routes/index.rs
  effis/src/routes/static_routes.rs
  integration-tests/Cargo.toml
  integration-tests/README.md
  integration-tests/src/main.rs
  oprish/Cargo.toml
  oprish/Dockerfile
  oprish/src/main.rs
  oprish/src/rate_limit.rs
  oprish/src/routes/messages/mod.rs
  oprish/src/routes/mod.rs
  oprish/src/tests.rs
  pandemonium/Cargo.toml
  pandemonium/Dockerfile
  pandemonium/src/main.rs
  test.py
  tests/Eludris.toml
  tests/test-image.png
  tests/test-other
  tests/test-text.txt
  tests/test-video.mp4
  todel/Cargo.toml
  todel/src/models/files.rs
  todel/src/models/logic/files.rs
Labels: documentation

#68 feat(cli): make eludris directory configurable
  .github/workflows/build-cli.yml
  Cargo.lock
  cli/Cargo.toml
  cli/src/attachments.rs
  cli/src/clean.rs
  cli/src/deploy.rs
  cli/src/lib.rs
  cli/src/logs.rs
  cli/src/main.rs
  cli/src/static_attachments.rs
  cli/src/stop.rs
  cli/src/update.rs
Labels: enhancement

#74 chore: tidy up some minor things
  .github/workflows/build-cli.yml
  docs/src/pages/reference/data_to_md.ts
  integration-tests/src/main.rs
Labels: enhancement

#75 feat: move migration handling from Effis over to Oprish
  Cargo.lock
  effis/Cargo.toml
  effis/Dockerfile
  effis/src/main.rs
  oprish/Cargo.toml
  oprish/Dockerfile
  oprish/src/database.rs
  oprish/src/main.rs
Labels: enhancement

#77 chore(docker): make pandemonium and effis depend on oprish
  docker-compose.override.yml
Labels: enhancement

#79 feat(cli): improve how the CLI's config directory is handled
  Cargo.lock
  cli/Cargo.toml
  cli/README.md
  cli/src/lib.rs
  cli/src/main.rs
  docs/src/content/docs/cli.md
Labels: enhancement

#80 feat(cli): allow users to configure their `.env` file while setting up their instance
  .env.example
  cli/src/deploy.rs
Labels: enhancement

#82 docs: update old OprishRateLimits exmaple
  todel/src/conf/oprish_rate_limits.rs
Labels: documentation

#84 docs: include the current eludris version in the doc's `/autodoc/index.json`
  autodoc.py
  docs/astro.config.mjs
  docs/src/components/Sidebar.astro
  docs/src/pages/reference/[...slug].astro
  docs/src/pages/reference/data_to_md.ts
Labels: documentation

#83 feat: add users model and migration
  codegen/src/autodoc/utils.rs
  migrations/20221128214127_files.sql
  migrations/20230527171822_users.sql
  todel/src/models/mod.rs
  todel/src/models/users.rs
Labels: enhancement

#86 docs: improve the consistency of the documentation of some fields
  todel/src/models/files.rs
  todel/src/models/info.rs
  todel/src/models/messages.rs
Labels: documentation

#87 refactor(todel): only include "private" user fields when the `logic` feature is enabled
  todel/src/models/users.rs
Labels: enhancement

#88 refactor(todel): remove the only internally used fields on the `User` struct
  todel/src/models/users.rs
Labels: enhancement

#89 refactor(todel): tidy up the pre-existing `IdGenerator` code
  effis/src/main.rs
  effis/src/routes/buckets.rs
  effis/src/routes/index.rs
  todel/src/ids/mod.rs
  todel/src/models/logic/files.rs
Labels: enhancement

#91 feat: migrate from MariaDB to PostgreSql
  .env.example
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
  cli/Cargo.toml
  cli/sqlx-data.json
  cli/src/attachments.rs
  cli/src/lib.rs
  docker-compose.override.yml
  docs/src/content/docs/conf.md
  docs/src/content/docs/hosting.md
  effis/Cargo.toml
  effis/Dockerfile
  effis/src/main.rs
  migrations/20221128214127_files.sql
  migrations/20230527171822_users.sql
  oprish/Cargo.toml
  oprish/Dockerfile
  oprish/src/main.rs
  pandemonium/Dockerfile
  tests/docker-compose.yml
  todel/Cargo.toml
  todel/sqlx-data.json
  todel/src/models/logic/files.rs
Labels: enhancement, absolutely based

#93 refactor(todel): clean up the `Conf` source code to be more maintainable
  todel/src/conf/effis.rs
  todel/src/conf/mod.rs
  todel/src/conf/oprish.rs
  todel/src/conf/pandemonium.rs
Labels: scope/todel, type/refactor
